### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jonkerj** [izer-xyz/librespot-openwrt#1]
Hi there, librespot 0.5.0 is out, can you please run your CI/CD to produce a new build?

**Comment by sinegar** [comment]
Just did it (will probably take at least 30 min). Doing a pre-release as iI don’t have time to test. Let me know how it goes.

**Comment by sinegar** [comment]
The old build failed. Got it fixed by bumping the OpenWrt version to the latest but there is still an issue as the new `librespot` has another dependency ( `bindgen-cli` ).

**Comment by jonkerj** [comment]
Sorry, I missed your message somehow. I'll give it a go in the coming days

**Comment by sinegar** [comment]
There is nothing to check the build failed. I need to fix the dependency.

**Comment by jonkerj** [comment]
for what's worth, your build/release from a few hours ago works perfectly. Thanks!

**Comment by sinegar** [comment]
Great! Thanks for checking it out. It was a long shot as I was not sure what I was doing… 

I saw there is a v0.6 - will give it a go later in the week.

**Comment by sinegar** [comment]
Did a successful build for v0.6. I close this ticket but leave the new build as a pre-release until I have time to test it.
