### ISSUE TITLE
Linksys WRT1900AC

### ISSUE THREAD

**Issue by betojsp** [izer-xyz/librespot-openwrt#2]
Hello, I have been looking for support for Spotify on OpenWrt, and I finally found it. I tried to compile it for this router using the Docker image of the SDK, but I was unsuccessful. Could you please help me with how to proceed?

Docker image https://hub.docker.com/r/openwrt/sdk/tags?name=mvebu-cortexa9

Thanks

**Comment by sinegar** [comment]
I have added a new target. You can download the package from here: 

 * https://github.com/izer-xyz/librespot-openwrt/releases/tag/v0.4.2-1_23.05.5_66

I don’t have time to test. Can you confirm that it’s working?

**Comment by betojsp** [comment]
Thanks @sinegar, it works well.

**Comment by sinegar** [comment]
Thanks for confirming.
