### ISSUE TITLE
Support to TP-Link TL-WDR4300 and TL-WDR3600

### ISSUE THREAD

**Issue by betojsp** [izer-xyz/librespot-openwrt#3]
Hello Péter, thank you once again for the package for the Linksys. It is working very well and without any issues. 
Could you please assist me in generating the package for these two routers? Thank you.

https://openwrt.org/toh/tp-link/tl-wdr4300_v1
https://openwrt.org/toh/tp-link/tl-wdr3600_v1

Thanks :)

**Comment by sinegar** [comment]
Librespot only works on arm or x86. These have mips chips. I don’t think it will work…

Anyway:

1.  find the right sdk image (tag) on docker hub - https://hub.docker.com/r/openwrt/sdk/tags
2. add the tag to the [build.yml](https://github.com/izer-xyz/librespot-openwrt/blob/59a1c61372be6e2a551ffb6cf155dfa7f11f292c/.github/workflows/build.yml#L21)
3. run the github action

**Comment by betojsp** [comment]
Thank you for the clarification. Unfortunately, support for this processor is not available.
